package com.ett.report;

public interface JRConstants {

    public static String REPORT_PARAMETER_CLIENT_ID = "CLIENT_ID";
    public static String REPORT_PARAMETER_ACCOUNT_ID = "ACCOUNT_ID";
    public static String REPORT_PARAMETER_ASSET_ID = "ASSET_ID";
    public static String REPORT_PARAMETER_TRADE_DATE_FROM = "TRADE_DATE_FROM";
    public static String REPORT_PARAMETER_TRADE_DATE_TO = "TRADE_DATE_TO";
    public static String REPORT_PARAMETER_TRADE_DATE_FROM_DATE = "TRADE_DATE_FROM_DATE";
    public static String REPORT_PARAMETER_TRADE_DATE_TO_DATE = "TRADE_DATE_TO_DATE";
    public static String REPORT_PARAMETER_RM_CODE = "RM_CODE";
    public static String REPORT_PARAMETER_VALUATION_DATE = "VALUATION_DATE";
    public static String REPORT_PARAMETER_MS_CLIENT_ID_LIST = "CLIENT_ID_LIST";
    public static String REPORT_PARAMETER_MS_CLIENT_NULL = "CLIENT_ID_NULL";
    public static String REPORT_PARAMETER_VALUATION_DATE_STR_FROM = "VALUATION_DATE_STR_FROM";
    public static String REPORT_PARAMETER_VALUATION_DATE_STR_TO = "VALUATION_DATE_STR_TO";
    public static String REPORT_PARAMETER_VALUATION_DATE_FROM = "VALUATION_DATE_FROM";
    public static String REPORT_PARAMETER_VALUATION_DATE_TO = "VALUATION_DATE_TO";

    public static String REPORT_PARAMETER_CLIENT_ID_LIST = "CLIENT_ID_LIST";
    public static String REPORT_PARAMETER_ACCOUNT_ID_LIST = "ACCOUNT_ID_LIST";
    public static String REPORT_PARAMETER_ASSET_ID_LIST = "ASSET_ID_LIST";
    public static String REPORT_PARAMETER_TRANS_TYPE_LIST = "TRANS_TYPE_LIST";
    public static String REPORT_PARAMETER_TRANS_EBIPO_TYPE = "TRANS_EBIPO_TYPE";
    public static String REPORT_PARAMETER_ORDERDETAIL_TYPE_LIST = "ORDERDETAIL_TYPE_LIST";
    public static String REPORT_PARAMETER_ORDERDETAIL_EBIPO_TYPE = "ORDERDETAIL_EBIPO_TYPE";
    public static String REPORT_PARAMETER_EXCEPTION_TYPE = "EXCEPTION_TYPE";
    public static String REPORT_PARAMETER_EXCEPTION_TYPE_ITEM = "EXCEPTION_TYPE_ITEM";
    public static String REPORT_PARAMETER_CROSS = "CROSS";
    public static String RISK_ASSESSMENT_PERIOD = "RISK_ASSESSMENT_PERIOD";

    public static String REPORT_PARAMETER_CLIENT_IDS = "CLIENT_IDS";
    public static String REPORT_PARAMETER_ASSET_IDS = "ASSET_IDS";

    public static String REPORT_PARAMETER_ACCOUNT_IDS = "ACCOUNT_IDS";

    //for export client
    public static String REPORT_PARAMETER_ASSESSMENTOPTION = "ASSESSMENT_OPTION";
    public static String REPORT_PARAMETER_SEARCHKEY = "SEARCH_KEY";

    //for export settleAccountEnquiry
    public static String REPORT_PARAMETER_SEARCHITEM = "SEARCH_ITEM";

    //for export CAM
    public static String REPORT_PARAMETER_CAM_ASOFDATE = "CAM_ASOFDATE_KEY";
    public static String REPORT_PARAMETER_CAM_ASSETID = "CAM_ASSETID_KEY";
    public static String REPORT_PARAMETER_CAM_TYPE = "CAM_TYPE_KEY";

    //for export instruction
    public static String REPORT_PARAMETER_QUERY_STRING = "QUERY_STRING";
    public static String REPORT_PARAMETER_PRODUCT_TYPE = "PRODUCT_TYPE";
    public static String REPORT_PARAMETER_INSTRUCTION_TYPE = "INSTRUCTION_TYPE";
    public static String REPORT_PARAMETER_CCY = "CCY";
    public static String REPORT_PARAMETER_APPLICATIONDATE_FROM = "APPLICATIONDATE_FROM";
    public static String REPORT_PARAMETER_APPLICATIONDATE_TO = "APPLICATIONDATE_TO";

    public static String REPORT_PARAMETER_INSTRUCTIONSTATUS_LIST = "INSTRUCTION_STATUS_LIST";

    public static String REPORT_PARAMETER_INSTRUCTIONPENDINGACTION_LIST = "INSTRUCTION_PENDING_ACTION_LIST";
    public static String REPORT_PARAMETER_INSTRUCTIONPENDINGSTATUS_LIST = "INSTRUCTION_PENDING_STATUS_LIST";
    public static String REPORT_PARAMETER_WARNING_TYPE = "WARNING_TYPE";

    //for grda monthly statement
    public static String REPORT_PARAMETER_STATEMENT_DATE_FROM = "DATE_FROM";
    public static String REPORT_PARAMETER_STATEMENT_DATE_TO = "DATE_TO";
    public static String REPORT_PARAMETER_STATEMENT_DATE_TO_DATETYPE = "DATE_TO_DATETYPE";
    public static String REPORT_PARAMETER_STATEMENT_DATE_YEAR = "DATE_YEAR";
    public static String REPORT_PARAMETER_STATEMENT_DATE_MONTH = "DATE_MONTH";
    public static String REPORT_PARAMETER_STATEMENT_DATA_FLAG = "DATA_FLAG";
    //public static String REPORT_PARAMETER_STATEMENT_DATE_YEAR_INT = "DATE_YEAR_INT";
    //public static String REPORT_PARAMETER_STATEMENT_DATE_MONTH_INT = "DATE_MONTH_INT";
    public static String REPORT_PARAMETER_CONSOLIDATED_CURRENCY = "CONSOLIDATED_CURRENCY";
    public static String REPORT_PARAMETER_CONSOLIDATED_CURRENCY_DESC = "CONSOLIDATED_CURRENCY_DESC";
    public static String REPORT_PARAMETER_STATEMENT_DATE_LAST_MONTH = "DATE_LAST_MONTH";
    public static String REPORT_PARAMETER_STATEMENT_DATE_LAST_MONTH_END_DAY = "DATE_LAST_MONTH_END_DAY";
    public static String REPORT_PARAMETER_DAILY_OR_MONTHLY_STATEMENT = "DAILY_OR_MONTHLY_STATEMENT";
    public static String REPORT_PARAMETER_AS_OF_DATE = "AS_OF_DATE";
    public static String REPORT_PARAMETER_SYS_TRADE_DATE = "SYS_TRADE_DATE";

    public static String REPORT_PARAMETER_PRICE_PATTERN = "PRICE_PATTERN";
    public static String REPORT_PARAMETER_PRICE_PATTERN_VALUE = "#,##0.00##";
    public static String REPORT_PARAMETER_AMT_PATTERN = "AMT_PATTERN";
    public static String REPORT_PARAMETER_AMT_PATTERN_VALUE = "#,##0.00";
    public static String REPORT_PARAMETER_QTY_PATTERN = "QTY_PATTERN";
    public static String REPORT_PARAMETER_QTY_PATTERN_VALUE = "#,##0.00";
    public static String REPORT_PARAMETER_EXCHANGE_RATE_PATTERN = "EXCHANGE_RATE_PATTERN";
    public static String REPORT_PARAMETER_EXCHANGE_RATE_PATTERN_VALUE = "#,##0.######";
    public static String REPORT_PARAMETER_RATE_PATTERN = "RATE_PATTERN";
    public static String REPORT_PARAMETER_RATE_PATTERN_VALUE = "#,##0.000000";
    

    public static String REPORT_PARAMETER_ALLOW_BACK_DATE = "ALLOW_BACK_DATE";
    public static String REPORT_PARAMETER_STATUS_LIST = "STATUS_LIST";
    public static String REPORT_PARAMETER_EXPORT_IPO_TYPE = "EXPORT_IPO_TYPE";
    
    public static String EXPORT_IPO_TYPE_SUBSCRIPTION = "Subscription";
    public static String EXPORT_IPO_TYPE_ALLOTMENT = "Allotment";
    
    //
    public static String REPORT_PARAMETER_ISSUER_ID = "ISSUER_ID ";
    public static String REPORT_PARAMETER_RISK_LEVEL = "RISK_LEVEL";
    public static String REPORT_PARAMETER_COUPON_RATE = "COUPON_RATE";

    public static String REPORT_PARAMETER_ACTION_START_DATE = "ACTION_START_DATE ";
    public static String REPORT_PARAMETER_ACTION_END_DATE = "ACTION_END_DATE";
    
    public static String REPORT_PARAMETER_EXTRANSREPORT_TYPE = "EXTRANSREPORT_TYPE ";
    
    public static String REPORT_PARAMETER_ORDER_DATE_FROM_DATE = "ORDER_DATE_FROM_DATE";
    public static String REPORT_PARAMETER_ORDER_DATE_TO_DATE = "ORDER_DATE_TO_DATE";
    
    public static String REPORT_PARAMETER_ORDER_ID = "ORDER_ID";
    public static String REPORT_PARAMETER_SENIOR_AGE = "SENIOR_AGE";
    
    public static String REPORT_PARAMETER_INSTRUCTION_ID = "INSTRUCTION_ID";
    
    public static String REPORT_PARAMETER_DIVIDEN_ACCOUNTID = "DIVIDEN_ACCOUNTID";
    public static String REPORT_PARAMETER_DIVIDEN_ASSETID = "DIVIDEN_ASSETID";
    public static String REPORT_PARAMETER_DIVIDEN_DIVIDENDDATE = "DIVIDEN_DIVIDENDDATE";
    public static String REPORT_PARAMETER_DIVIDEN_FUNDHSEID = "DIVIDEN_FUNDHSEID";
    public static String REPORT_PARAMETER_DIVIDEN_PRODUCTTYPE = "DIVIDEN_PRODUCTTYPE";
    public static String REPORT_PARAMETER_DIVIDEN_ISDIVIDEND = "DIVIDEN_ISDIVIDEND";
    public static String REPORT_PARAMETER_DIVIDEN_ISMATURITY = "DIVIDEN_ISMATURITY";
    public static String REPORT_PARAMETER_DIVIDEN_ISQTYABOVE0 = "DIVIDEN_ISQTYABOVE0";
    public static String REPORT_PARAMETER_DIVIDEN_DIVIDEND_UNSETTLE_QTY_INCLUDED = "DIVIDEND_UNSETTLE_QTY_INCLUDED";
    
    //for erp invoice
    public static String REPORT_PARAMETER_INVOICE_ID = "INVOICE_ID";

    public static String REPORT_PARAMETER_ADJ_ID = "ADJ_ID";
    public static String REPORT_PARAMETER_GRN_ID = "GRN_ID";

    // inventory_adj
    public static String REPORT_PARAMETER_INPUT_DATE_FROM_DATE = "INPUT_DATE_FROM_DATE";
    public static String REPORT_PARAMETER_INPUT_DATE_TO_DATE = "INPUT_DATE_TO_DATE";
}
